### ISSUE TITLE
Compiling with shared objects & 32-bit support

### ISSUE THREAD

**Issue by ndfriedmanLRS** [ZOSOpenTools/opensslport#42]
Hello,

I am attempting to integrate OpenSSL into an existing project using this port and the zopen build tool, and for my purposes it is necessary to have libssl and libcrypto available as shared objects compiled in 32-bit mode (as the underlying project is using AMODE 31). So far I have been able to successfully compile and link the shared objects in 64-bit mode, but I am having some trouble with the linking process in 32-bit mode. The compiler I am using is the Open XL v2.1 ibm-clang, and with the -m32 flag specified it is able to successfully compile up to the linking phase. 

Upon trying to link libcrypto, however, a number of errors are thrown related to conflicting AMODEs between a referencing ESD and the import statement, with the import statement in question being a 32-bit CODE import from the standard C Runtime Library, and the ESD coming from the (presumably 64-bit) zoslib modules. This also throws a separate error about both C_WSA and C_WSA64 being present in the module, due to the mixed AMODEs between the zoslib and OpenSSL object files.

From my understanding, this conflict is arising from zoslib being only available in 64-bit mode, and thus being unable to include the 32-bit runtime library that is required for the rest of the project (as well as being unable to be properly linked into a 32-bit libcrypto module altogether). I'm not sure if this is a question better served for the zoslib project, as I have also separately been unable to build zoslib in 32-bit mode myself, or if there is a way to bypass this requirement or use zoslib as-is in 32-bit mode.

This project has already been an enormous help, and I appreciate any help you may be able to provide in advance.

**Comment by IgorTodorovskiIBM** [comment]
Porting zoslib to 32-bit may take a lot of effort. You could first try building without zoslib by adding this to the buildenv: https://github.com/zopencommunity/zos-code-page-toolsport/blob/main/buildenv#L8.

**Comment by IgorTodorovskiIBM** [comment]
Yep, zoslib just adds a stub for param.h to avoid the error
